services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
